name: Build sing-box
on:
  watch:
    types: started
  workflow_dispatch:

jobs:
  build-xray-core:
    if: github.event.repository.owner.id == github.event.sender.id
    runs-on: ubuntu-latest

    steps:
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.22
        check-latest: true

    - name: Clone Xray-core Source
      run: |
        git clone https://github.com/seav1/singbox
        cd singbox
        go mod download

    - name: Get Latest Release
      run: |
        RELEASE_TITLE=$(curl -s https://api.github.com/repos/SagerNet/sing-box/releases | jq -r 'first(.[]).name')
        echo "release_title=$RELEASE_TITLE" >> $GITHUB_ENV
        RELEASE_COMMITS=$(curl -s https://api.github.com/repos/SagerNet/sing-box/commits/main | grep -oP '"sha": "\K(.*)(?=")' | head -1)
        echo "release_commits=$RELEASE_COMMITS" >> $GITHUB_ENV
        echo "https://github.com/SagerNet/sing-box/commit/$RELEASE_COMMITS"

    - name: Build for AMD64
      run: |
        cd singbox
        go env -w CGO_ENABLED=0 GOOS=linux GOARCH=amd64
        go build -v -o sing-box-amd64 -trimpath -ldflags "-s -w -buildid=" ./main

    - name: Build for ARM64
      run: |
        cd singbox
        go env -w CGO_ENABLED=0 GOOS=linux GOARCH=arm64
        go build -v -o sing-box-arm64 -trimpath -ldflags "-s -w -buildid=" ./main

    - name: Build for AMD64
      run: |
        cd singbox
        go env -w CGO_ENABLED=0 GOOS=freebsd GOARCH=amd64
        go build -v -o sing-box-freebsd-amd64 -trimpath -ldflags "-s -w -buildid=" ./main

    - name: Delete current release assets
      uses: andreaswilli/delete-release-assets-action@v3.0.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        tag: latest
        deleteOnlyFromDrafts: false

    - name: Create and Upload Release
      id: upload_release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        release_name: ${{env.release_title}}
        tag: latest
        body: |
          Latest commit from the main branch:
          https://github.com/XTLS/Xray-core/commit/${{env.release_commits}}
        file_glob: true
        overwrite: true
        file: ./Xray-core/xray-*
